backend:
  name: git-gateway
  branch: master
  repo: ACollectionOfAtoms/mhd

media_folder: static/img
public_folder: /img

collections:
  - name: "about"
    label: "About"
    folder: "src/pages/about-blurb"
    create: true
    fields: 
      - {label: "About Section", name: "body", widget: "markdown" }
