backend:
  name: git-gateway
  branch: master
  repo: ACollectionOfAtoms/mhd

media_folder: static/img
public_folder: /img

collections:
  - name: "About Blurb"
    label: "about blurb"
    folder: "src/pages/about-blurbs"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
